src/Entity/Vol.php
<?php

namespace App\Entity;

use App\Repository\VolRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=VolRepository::class)
 */
class Vol
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("vols")
     */
    private $id;

    /**
     * @Groups("vols")
     * @ORM\Column(type="date")
     */
    private $Datedepart;

    /**
     * @Groups("vols")
     * @ORM\Column(type="date")
     */
    private $Datearrive;

    /**
     * @Assert\NotBlank
     * @Assert\Length(
     * min=3,max=15,
     * minMessage ="Le nom du vol doit contenir au moins 3 caractere",
     * maxMessage ="Le nom du vol doit contenir 15 caractere Maximum")
     * @ORM\Column(type="string", length=30)
     * @Groups("vols")
     */
    private $nom;

    /**
     * @Groups("vols")
     * @ORM\Column(type="time")
     */
    private $heuredepart;

    /**
     * @Groups("vols")
     * @ORM\Column(type="time")
     */
    private $heurearrive;

    /**
     * @Groups("vols")
     * @Assert\NotBlank
     * @Assert\Length(
     * min=3,max=15,
     * minMessage ="La destination du vol doit contenir au moins 3 caractere",
     * maxMessage ="La destination du vol doit contenir 15 caractere Maximum")
     * @ORM\Column(type="string", length=30)
     */
    private $destination;

    /**
     * @Groups("vols")
     * @Assert\Positive
     * @ORM\Column(type="integer")
     */
    private $nbrplace;



    /**
     * @ORM\ManyToOne(targetEntity=Airline::class, inversedBy="vols")
     */
    private $airline;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDatedepart(): ?\DateTimeInterface
    {
        return $this->Datedepart;
    }

    public function setDatedepart(\DateTimeInterface $Datedepart): self
    {
        $this->Datedepart = $Datedepart;

        return $this;
    }

    public function getDatearrive(): ?\DateTimeInterface
    {
        return $this->Datearrive;
    }

    public function setDatearrive(\DateTimeInterface $Datearrive): self
    {
        $this->Datearrive = $Datearrive;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getHeuredepart(): ?\DateTimeInterface
    {
        return $this->heuredepart;
    }

    public function setHeuredepart(\DateTimeInterface $heuredepart): self
    {
        $this->heuredepart = $heuredepart;

        return $this;
    }

    public function getHeurearrive(): ?\DateTimeInterface
    {
        return $this->heurearrive;
    }

    public function setHeurearrive(\DateTimeInterface $heurearrive): self
    {
        $this->heurearrive = $heurearrive;

        return $this;
    }

    public function getDestination(): ?string
    {
        return $this->destination;
    }

    public function setDestination(string $destination): self
    {
        $this->destination = $destination;

        return $this;
    }

    public function getNbrplace(): ?int
    {
        return $this->nbrplace;
    }

    public function setNbrplace(int $nbrplace): self
    {
        $this->nbrplace = $nbrplace;

        return $this;
    }


    public function getAirline(): ?Airline
    {
        return $this->airline;
    }

    public function setAirline(?Airline $airline): self
    {
        $this->airline = $airline;

        return $this;
    }

}

src/Form/VolType.php
<?php

namespace App\Form;

use App\Entity\Airline;
use App\Entity\Vol;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VolType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Datedepart')
            ->add('Datearrive')
            ->add('nom')
            ->add('heuredepart')
            ->add('heurearrive')
            ->add('destination')
            ->add('nbrplace')
            ->add('Airline' , EntityType::class,
                [
                    'class'=>Airline::class,
                    'choice_label' => 'nomairline'


                ])
            ->add('Submit',SubmitType::class);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Vol::class,
        ]);
    }
}

src/Controller/VolController.php
<?php

namespace App\Controller;

use App\Entity\Vol;
use App\Form\VolType;
use App\Repository\AirlineRepository;
use App\Repository\VolRepository;
use http\Env\Url;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use MercurySeries\FlashyBundle\FlashyNotifier;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Dompdf\Dompdf;
use Dompdf\Options;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Component\Serializer\SerializerInterface;




class VolController extends AbstractController
{


    /**
     * @Route("/", name="main")
     */
    public function index1()
    {
        return $this->render('PagePrincipal/Main.html.twig');
    }


    /**
     * @Route("/vol", name="app_vol")
     */
    public function index(): Response
    {
        $vols = $this->getDoctrine()->getManager()->getRepository(Vol::class)->findALL();
        return $this->render('vol/index.html.twig',
            ['vols' => $vols]);
    }

    /**
     * @Route("/addvol", name="addvol")
     */

    public function addVol(Request $request,FlashyNotifier $flashy):Response
    {
        $vol = new Vol();

        $form = $this->createForm(VolType::class, $vol);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($vol);//Add
            $em->flush();
            $flashy->success("Vol Ajouter avec Succés",'vol');
            return $this->redirectToRoute('app_vol');

        }

        return $this->render('vol/Createvol.html.twig', ['f' => $form->createView()]);

    }

    /**
     * @Route("/removevol/{id}",name="supp_vol")
     */
    public function suppressionVol(Vol $vol,FlashyNotifier $flashy): Response
    {

        $em = $this->getDoctrine()->getManager();
        $em->remove($vol);
        $em->flush();
        $flashy->success("Vol Supprimer avec Succés",'vol');
        return $this->redirectToRoute('app_vol');

    }

    /**
     * @Route("/editvol/{id}", name="editvol")
     */

    public function editvol(Request $request,$id,FlashyNotifier $flashy): Response
    {
        $vol = $this->getDoctrine()->getManager()->getRepository(Vol::class)->find($id);

        $form = $this->createForm(VolType::class, $vol);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $em = $this->getDoctrine()->getManager();
            $em->flush();
            $flashy->info("Vol modifié",'vol');
            return $this->redirectToRoute('app_vol');
        }
        return $this->render('vol/updatevol.html.twig', ['f' => $form->createView()]);

    }


    /**
     * @param VolRepository $repository
     * @Route("/volliste",name="volliste")
     */

    public function Affichagelistedesvolsdispo(VolRepository $repository)
    {


        $em = $this->getDoctrine()->getManager();

        //$re=$em->CreateQuery('SELECT v FROM App\Entity\Vol v')->getResult();

        /*$re = $em->CreateQuery('SELECT count(v) FROM App\Entity\Vol v ')->getResult();

        dump($re[0][1]);
        die;*/
        /*   $re = $em->CreateQuery('SELECT count(v) FROM App\Entity\Vol v ')->getSingleScalarResult(); //retourne une seul valeur et pas un array
        dump($re);
        die;
        */

        $best = $em->CreateQuery
        (

            "  
            
    SELECT v.nom,v.Datedepart,v.Datearrive,v.heuredepart,v.heurearrive,v.destination,a.nomairline,v.nbrplace
    FROM App\Entity\Vol v INNER JOIN App\Entity\Airline a
    where a.id = v.airline
    
            "
        )
            ->getResult();

        return $this->render('vol/listevoluser.html.twig',
            ['best' => $best]);

        /*dump($best);
        die;*/


    }



     /**
     * @param VolRepository $repository
     * @Route("/vol", name="app_vol")
     */

    public function rechercheByNomAction(Request $request,FlashyNotifier $flashy,FlashyNotifier $flashy1)
    {
        $em = $this->getDoctrine()->getManager();
        $vols = $em->getRepository(Vol::class)->findAll();


        if ($request->isMethod("POST"))
        {

            $nom = $request->get('nom');
            $vols = $em->getRepository(Vol::class)->findBy(array('nom' => $nom));
            $flashy->success("Liste des vols avec le nom :".$nom, 'vol');

        }


        return $this->render('vol/index.html.twig', array('vols' => $vols));
    }











    /**
     * @Route("/imprimer", name="imprimer")
     */

    public function imprimer()
    {


        $vols = $this->getDoctrine()->getManager()->getRepository(Vol::class)->findALL();


        // Configure Dompdf according to your needs
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');

        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);

        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('vol/index.html.twig',
            ['vols' => $vols]);

        // Load HTML to Dompdf
        $dompdf->loadHtml($html);

        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A4', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser (force download)
        $dompdf->stream("mypdf.pdf", [
            "Attachment" => true
        ]);
    }


    /**
     * @Route("/addVolJson/new",name="addVolJson")
     */

public function addVoljson(Request $request,NormalizerInterface $Normalizer)
{
    $em=$this->getDoctrine()->getManager();
    $Vol = new Vol();
    /*\DateTime::createFromFormat('Y-m-d');*/


    $Vol->setNom($request->get('Nom'));
  /*  $Vol->setDatearrive($request->get('Datearrive'));*/

    $Vol->setDatearrive(\DateTime::createFromFormat('Y-m-d',$request->get('Datearrive')));

    $Vol->setDatedepart(\DateTime::createFromFormat('Y-m-d',$request->get('Datedepart')));


  /* $Vol->setDatedepart($request->get('Datedepart'));*/
    $Vol->setDestination($request->get('destination'));
 /*  $Vol->setHeurearrive($request->get('Heurearrive'));
    $Vol->setHeuredepart($request->get('Heuredepart'));*/


    $Vol->setHeurearrive(\DateTime::createFromFormat('H:i:s',$request->get('Heurearrive')));

    $Vol->setHeuredepart(\DateTime::createFromFormat('H:i:s',$request->get('Heuredepart')));

    $Vol->setNbrplace($request->get('nbrplace'));

    $Vol->setAirline($request->get('Airline'));
    $em->persist($Vol);
    $em->flush();
    $jsonContent = $Normalizer->normalize($Vol,'json',['groups'=>'post:read']);
return new Response(json_encode($jsonContent));
}


    /**
     * @Route("/jsonvos", name="jsonvls")
     */
    public function getvols(VolRepository $repo,SerializerInterface $serializerinterface)
    {

        $vols = $repo->findAll();
        $json=$serializerinterface->serialize($vols,'json',['groups'=>'vols']);
        dump($json);
        die;


    }

    /**
     * @Route("/Updatevoljson/{id}",name="Updatevoljson")
     */

    public function updatevolJson(Request $request,NormalizerInterface $normalizer,$id)
    {
        $em= $this->getDoctrine()->getManager();
        $Vol= $em->getRepository(Vol::class)->find($id);

        $Vol->setNom($request->get('Nom'));
        $Vol->setDatearrive(\DateTime::createFromFormat('Y-m-d',$request->get('Datearrive')));
        $Vol->setDatedepart(\DateTime::createFromFormat('Y-m-d',$request->get('Datedepart')));
        $Vol->setDestination($request->get('destination'));
        $Vol->setHeurearrive(\DateTime::createFromFormat('H:i:s',$request->get('Heurearrive')));
        $Vol->setHeuredepart(\DateTime::createFromFormat('H:i:s',$request->get('Heuredepart')));
        $Vol->setNbrplace($request->get('nbrplace'));
        $Vol->setAirline($request->get('Airline'));
        $em->flush();
        $jsonContent = $normalizer->normalize($Vol,'json',['groups'=>'post:read']);

        return new Response("Updated".json_encode($jsonContent));



    }

    /**
     * @Route("/jsonvols", name="jsonvols")
     */
public function Allvols(NormalizerInterface $normalizer)
{

    $repository = $this->getDoctrine()->getRepository(Vol::class);
    $vols = $repository->findAll();

    $jsonContent = $normalizer->normalize($vols,'json',['groups'=>'vols']);




    return new Response(json_encode($jsonContent) );
}


    /**
     * @Route("/deletevolJson/{id}", name="deletevolJson")
     */
    public function deletevolJson(Request $request,NormalizerInterface $Normalizer,$id)
    {
        $em = $this->getDoctrine()->getManager();
        $vols = $em->getRepository(Vol::class)->find($id);
        $em->remove($vols);
        $em->flush();
        $jsonContent = $Normalizer->normalize($vols,'json',['groups'=>'post:read']);
        return new Response("Deleted !!".json_encode($jsonContent));
    }






}

templates/vol/Createvol.html.twig
{% extends 'Back/base.html.twig' %}



{% block title %} Ajouter un vol {% endblock %}

{% block body %}
    <center>
        <h1 class=> Ajouter un vol  </h1>
    </center>
    <center>
{{ form_start(f,{attr:{novalidate:'novalidate'}}) }}
<table>
    <tr>
        <td>{{ form_label(f.Datedepart,"Date de depart")}} </td>
        <td>{{ form_widget(f.Datedepart) }} {{ form_errors(f.Datedepart) }}</td>

    </tr>

    <tr>
        <td>{{ form_label(f.Datearrive,"Date d'arrive")}} </td>
        <td>{{ form_widget(f.Datearrive) }} {{ form_errors(f.Datearrive) }}</td>
    </tr>


    <tr>
        <td>{{ form_label(f.destination,"Destination")}} </td>
        <td>{{ form_widget(f.destination) }} {{ form_errors(f.destination) }}</td>
    </tr>


    <tr>
        <td>{{ form_label(f.nbrplace,"Nombre de place ")}} </td>
        <td>{{ form_widget(f.nbrplace) }} {{ form_errors(f.nbrplace) }}</td>
    </tr>

    <tr>
        <td>{{ form_label(f.heuredepart,"Heure de depart")}} </td>
        <td>{{ form_widget(f.heuredepart) }} {{ form_errors(f.heuredepart) }}</td>
    </tr>


    <tr>
        <td>{{ form_label(f.heurearrive,"Heure d'arrive")}} </td>
        <td>{{ form_widget(f.heurearrive) }} {{ form_errors(f.heurearrive) }}</td>
    </tr>

    <tr>
        <td>{{ form_label(f.nom,"Nom de Vol")}} </td>
        <td>{{ form_widget(f.nom) }} {{ form_errors(f.nom) }}</td>
    </tr>
{#
    <tr>
        <td>{{ form_label(f.nomairline,"Nom de airline")}} </td>
        <td>{{ form_widget(f.nomairline) }} {{ form_errors(f.nomairline) }}</td>
    </tr>
#}



    <tr>

    </tr>







</table>






{{ form_end(f) }}
    </center>
{% endblock %}

templates/vol/index.html.twig
{% extends 'Back/base.html.twig' %}

{% block title %}Liste des Vols{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>
    <center>
    <h1 class="titreadmin"> Liste des Vols</h1>
    </center>






    <div>

        <table border=2px class="e">


            <th class="s" >Nom vol</th>
            <th class="s">Date de depart</th>
            <th class="s">Date d'arrivé </th>
            <th class="s">Destination</th>
            <th class="s">Nombre de place</th>
            <th class="s">Heure de depart</th>
            <th class="s">Heure d'arrive</th>

          {# <th class="prize-comp">Nom Airline</th>#}
            <th class="s"></th>
            <th class="s"></th>



            {%for v in vols%}
                <tr class="f">

                    <td class="s" >{{v.nom}}</td>
                    <td  class="s">{{v.datedepart|date('Y-m-d')}} </td>
                    <td  class="s">{{v.datearrive|date('Y-m-d')}} </td>
                    <td class="s">{{v.destination}}</td>
                    <td class="s">{{v.nbrplace}}</td>
                    <td class="s">{{v.heuredepart|date('H:i:s')}}</td>
                    <td class="s">{{v.heurearrive|date('H:i:s')}}</td>

            {#  <td class="prize-comp">{{v.nomairline}}</td> #}

                    <td class="del">
                        <a href="{{ path('supp_vol',{'id':v.id}) }}"> Supprimer</a>
                    </td>
                    <td class="modifier">
                        <a href="{{ path('editvol',{'id':v.id}) }}"> Modifier</a>
                    </td>



                </tr>
            {% endfor %}

            <center>
                    <form class="right"  method="POST">
                    Donner le nom du vol
                    <input type="text" name="nom">
                    <input type="submit" value="recherche">





                </form>
                <a class="button-1"
                   href="{{ path('imprimer') }}"> Imprimer
                </a>
            </center>

            </form>




        </table>




    </div>



{% endblock %}

templates/vol/listevoluser.html.twig
{% extends 'Front/template.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<center>
    <h1 class="titreadmin"> Vols Disponibles  </h1>
</center>

<div class="example-wrapper">
    <center>
        <table border="1" class="jointure">

            {#  <th class="jointure" >Nom de Airline</th>
    <th class="jointure">Id de vol </th>
    <th class="jointure">Nom de vol</th>
            #}














            {%for b in best%}
    {#  <tr class="jointure">
        <td class="jointure">{{b.nom}} </td>
        <td class="jointure"> {{b.id}} </td>
        <td class="jointure">{{b.nomvol}}</td>
    </tr>#}


                <div class="container">
                    <div class="card">
                        <div class="box">
                            <div class="content">
                                <h2>{{b.nbrplace}} </h2>
                                <h3>Airline: {{b.nomairline}}</h3>
                                <h3>Vol: {{b.nom}}</h3>
                                <h4>Depart:{{ b.Datedepart|date('Y-m-d')}}</h4>
                                <h4>Arrive:{{ b.Datearrive|date('Y-m-d')}} </h4>
            <p>        <br>   Heure depart   :{{ b.heuredepart|date('H:i:s')}}
                <br>   Heure arrive :{{ b.heurearrive|date('H:i:s')}}
                <br>      Destination:  {{ b.destination}}
                                 </p>
                                <a href="#">Read More</a>
                            </div>
                        </div>
                    </div>




            {% endfor %}


                </div>
        </table>
    </center>
</div>
{% endblock %}

templates/vol/updatevol.html.twig
{% extends 'Back/base.html.twig' %}



{% block title %} Modifier un vol {% endblock %}

{% block body %}
    <center>
        <h1 class=> Modifier un vol  </h1>
    </center>
    <center>
        {{ form_start(f,{attr:{novalidate:'novalidate'}}) }}
        <table>
            <tr>
                <td>{{ form_label(f.Datedepart,"Date de depart")}} </td>
                <td>{{ form_widget(f.Datedepart) }} {{ form_errors(f.Datedepart) }}</td>

            </tr>

            <tr>
                <td>{{ form_label(f.Datearrive,"Date d'arrive")}} </td>
                <td>{{ form_widget(f.Datearrive) }} {{ form_errors(f.Datearrive) }}</td>
            </tr>


            <tr>
                <td>{{ form_label(f.destination,"Destination")}} </td>
                <td>{{ form_widget(f.destination) }} {{ form_errors(f.destination) }}</td>
            </tr>


            <tr>
                <td>{{ form_label(f.nbrplace,"Nombre de place ")}} </td>
                <td>{{ form_widget(f.nbrplace) }} {{ form_errors(f.nbrplace) }}</td>
            </tr>

            <tr>
                <td>{{ form_label(f.heuredepart,"Heure de depart")}} </td>
                <td>{{ form_widget(f.heuredepart) }} {{ form_errors(f.heuredepart) }}</td>
            </tr>


            <tr>
                <td>{{ form_label(f.heurearrive,"Heure d'arrive")}} </td>
                <td>{{ form_widget(f.heurearrive) }} {{ form_errors(f.heurearrive) }}</td>
            </tr>

            <tr>
                <td>{{ form_label(f.nom,"Nom de Vol")}} </td>
                <td>{{ form_widget(f.nom) }} {{ form_errors(f.nom) }}</td>
            </tr>





        </table>

        {{ form_end(f) }}
    </center>
{% endblock %}